TRUNCATE TABLE B_FORM
/
TRUNCATE TABLE B_FORM_2_MAIL_TEMPLATE
/
TRUNCATE TABLE B_FORM_2_SITE
/
TRUNCATE TABLE B_FORM_ANSWER
/
TRUNCATE TABLE B_FORM_FIELD
/
TRUNCATE TABLE B_FORM_FIELD_FILTER
/
TRUNCATE TABLE B_FORM_FIELD_VALIDATOR
/
TRUNCATE TABLE B_FORM_MENU
/
TRUNCATE TABLE B_FORM_RESULT
/
TRUNCATE TABLE B_FORM_RESULT_ANSWER
/
TRUNCATE TABLE B_FORM_2_GROUP
/
TRUNCATE TABLE B_FORM_STATUS_2_GROUP
/
TRUNCATE TABLE B_FORM_STATUS
/
