DROP TABLE B_FORM CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_FORM
/

DROP TABLE B_FORM_2_MAIL_TEMPLATE CASCADE CONSTRAINTS
/

DROP TABLE B_FORM_2_SITE CASCADE CONSTRAINTS
/

DROP TABLE B_FORM_ANSWER CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_FORM_ANSWER
/

DROP TABLE B_FORM_FIELD CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_FORM_FIELD
/

DROP TABLE B_FORM_FIELD_FILTER CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_FORM_FIELD_FILTER
/

DROP TABLE B_FORM_FIELD_VALIDATOR CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_FORM_FIELD_VALIDATOR
/

DROP TABLE B_FORM_MENU CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_FORM_MENU
/

DROP TABLE B_FORM_RESULT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_FORM_RESULT
/

DROP TABLE B_FORM_RESULT_ANSWER CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_FORM_RESULT_ANSWER
/

DROP TABLE B_FORM_2_GROUP CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_FORM_2_GROUP
/

DROP FUNCTION CONVERT_TO_NUMBER
/

DROP TABLE B_FORM_STATUS CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_FORM_STATUS
/

DROP TABLE B_FORM_STATUS_2_GROUP CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_FORM_STATUS_2_GROUP
/
