DROP TABLE B_BLOG_SITE_PATH CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_BLOG_SITE_PATH
/
DROP TABLE B_BLOG CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_BLOG
/
DROP TABLE B_BLOG_GROUP CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_BLOG_GROUP
/
DROP TABLE B_BLOG_POST CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_BLOG_POST
/
DROP TABLE B_BLOG_CATEGORY CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_BLOG_CATEGORY
/
DROP TABLE B_BLOG_COMMENT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_BLOG_COMMENT
/
DROP TABLE B_BLOG_USER CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_BLOG_USER
/
DROP TABLE B_BLOG_USER_GROUP CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_BLOG_USER_GROUP
/
DROP TABLE B_BLOG_USER2USER_GROUP CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_BLOG_USER2USER_GROUP
/
DROP TABLE B_BLOG_USER_GROUP_PERMS CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_BLOG_USER_GROUP_PERMS
/
DROP TABLE B_BLOG_TRACKBACK CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_BLOG_TRACKBACK
/
DROP TABLE B_BLOG_SMILE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_BLOG_SMILE
/
DROP TABLE B_BLOG_SMILE_LANG CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_BLOG_SMILE_LANG
/
DROP TABLE B_BLOG_USER2BLOG CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_BLOG_USER2BLOG
/
DROP TABLE b_blog_image
/
DROP SEQUENCE SQ_B_BLOG_IMAGE
/
