DROP TABLE B_BLOG_SITE_PATH
GO
DROP TABLE B_BLOG
GO
DROP TABLE B_BLOG_GROUP
GO
DROP TABLE B_BLOG_POST
GO
DROP TABLE B_BLOG_CATEGORY
GO
DROP TABLE B_BLOG_COMMENT
GO
DROP TABLE B_BLOG_USER
GO
DROP TABLE B_BLOG_USER_GROUP
GO
DROP TABLE B_BLOG_USER2USER_GROUP
GO
DROP TABLE B_BLOG_USER_GROUP_PERMS
GO
DROP TABLE B_BLOG_TRACKBACK
GO
DROP TABLE B_BLOG_SMILE
GO
DROP TABLE B_BLOG_SMILE_LANG
GO
DROP TABLE B_BLOG_USER2BLOG
GO
DROP TABLE B_BLOG_IMAGE
GO
