ALTER TABLE B_FORUM DROP CONSTRAINT FK_B_FORUM_B_USER
GO
ALTER TABLE B_FORUM_TOPIC DROP CONSTRAINT FK_B_FORUM_TOPIC_B_USER
GO
ALTER TABLE B_FORUM_TOPIC DROP CONSTRAINT FK_B_FORUM_TOPIC_B_USER1
GO
ALTER TABLE B_FORUM_TOPIC DROP CONSTRAINT FK_B_FORUM_TOPIC_B_FORUM_SMILE
GO
ALTER TABLE B_FORUM_TOPIC DROP CONSTRAINT FK_B_FORUM_TOPIC_B_FORUM
GO
ALTER TABLE B_FORUM_MESSAGE DROP CONSTRAINT FK_B_FORUM_MESSAGE_B_USER
GO
ALTER TABLE B_FORUM_MESSAGE DROP CONSTRAINT FK_B_FORUM_MESSAGE_B_FORUM
GO
ALTER TABLE B_FORUM_MESSAGE DROP CONSTRAINT FK_B_FORUM_MESSAGE_B_FORUM_TOPIC
GO
ALTER TABLE B_FORUM_USER DROP CONSTRAINT FK_B_FORUM_USER_B_USER
GO
ALTER TABLE B_FORUM_PERMS DROP CONSTRAINT FK_B_FORUM_PERMS_B_FORUM
GO
ALTER TABLE B_FORUM_PERMS DROP CONSTRAINT FK_B_FORUM_PERMS_B_GROUP
GO
ALTER TABLE B_FORUM_SUBSCRIBE DROP CONSTRAINT FK_FORUM_SUBSCRIBE_USER
GO
ALTER TABLE B_FORUM_SUBSCRIBE DROP CONSTRAINT FK_FORUM_SUBSCRIBE_FORUM
GO
ALTER TABLE B_FORUM_SUBSCRIBE DROP CONSTRAINT FK_FORUM_SUB_FORUM_TOPIC
GO

DROP TABLE B_FORUM_SMILE
GO
DROP TABLE B_FORUM
GO
DROP TABLE B_FORUM_TOPIC
GO
DROP TABLE B_FORUM_MESSAGE
GO
DROP TABLE B_FORUM_USER
GO
DROP TABLE B_FORUM_PERMS
GO
DROP TABLE B_FORUM_SUBSCRIBE
GO
DROP TABLE B_FORUM_RANK
GO
DROP TABLE B_FORUM_RANK_LANG
GO
DROP TABLE B_FORUM_GROUP
GO
DROP TABLE B_FORUM_GROUP_LANG
GO
DROP TABLE B_FORUM_SMILE_LANG
GO
DROP TABLE B_FORUM_POINTS
GO
DROP TABLE B_FORUM_POINTS_LANG
GO
DROP TABLE B_FORUM_POINTS2POST
GO
DROP TABLE B_FORUM_USER_POINTS
GO
DROP TABLE B_FORUM2SITE
GO

ALTER TABLE B_FORUM_PRIVATE_MESSAGE DROP CONSTRAINT PK_B_FORUM_PRIVATE_MESSAGE
GO
DROP INDEX I_PM_USER_ID ON B_FORUM_PRIVATE_MESSAGE
GO
DROP INDEX I_PM_FOLDER_ID ON B_FORUM_PRIVATE_MESSAGE
GO
DROP TABLE B_FORUM_PRIVATE_MESSAGE
GO
ALTER TABLE B_FORUM_PM_FOLDER DROP CONSTRAINT PK_B_FORUM_PM_FOLDER
GO
DROP INDEX IX_PMF_FOLDER_ID ON B_FORUM_PM_FOLDER 
GO
DROP TABLE B_FORUM_PM_FOLDER
GO
ALTER TABLE B_FORUM_FILTER DROP CONSTRAINT PK_B_FORUM_FILTER_KEY
GO
DROP INDEX IX_B_FORUM_FILTER_2 ON B_FORUM_FILTER 
GO
DROP INDEX IX_B_FORUM_FILTER_3 ON B_FORUM_FILTER 
GO
DROP TABLE B_FORUM_FILTER
GO
ALTER TABLE B_FORUM_DICTIONARY DROP CONSTRAINT PK_B_FORUM_DICTIONARY 
GO
DROP TABLE B_FORUM_DICTIONARY
GO
ALTER TABLE B_FORUM_LETTER DROP CONSTRAINT PK_B_FORUM_LETTER
GO
DROP INDEX UX_B_FORUM_LETTER ON B_FORUM_LETTER
GO
DROP TABLE B_FORUM_LETTER
GO
ALTER TABLE B_FORUM_USER_TOPIC DROP CONSTRAINT PK_B_FORUM_USER_TOPIC
GO
DROP TABLE B_FORUM_USER_TOPIC
GO
ALTER TABLE B_FORUM_USER_FORUM DROP CONSTRAINT PK_B_FORUM_USER_FORUM
GO
DROP INDEX IX_B_FORUM_USER_FORUM ON B_FORUM_USER_FORUM
GO
DROP TABLE B_FORUM_USER_FORUM
GO
DROP INDEX IX_B_FORUM_STAT_TOPIC_ID ON B_FORUM_STAT
GO
DROP INDEX IX_B_FORUM_STAT_FORUM_ID ON B_FORUM_STAT
GO
DROP INDEX IX_B_FORUM_STAT_PHPSESSID ON B_FORUM_STAT
GO
DROP TABLE B_FORUM_STAT
GO
DELETE FROM B_EVENT_TYPE WHERE EVENT_NAME='NEW_FORUM_MESSAGE'
GO
DELETE FROM B_EVENT_TYPE WHERE EVENT_NAME='EDIT_FORUM_MESSAGE'
GO
DELETE FROM B_EVENT_TYPE WHERE EVENT_NAME='NEW_FORUM_PRIV'
GO
DELETE FROM B_EVENT_MESSAGE WHERE EVENT_NAME='NEW_FORUM_MESSAGE'
GO
DELETE FROM B_EVENT_MESSAGE WHERE EVENT_NAME='EDIT_FORUM_MESSAGE'
GO
DELETE FROM B_EVENT_MESSAGE WHERE EVENT_NAME='NEW_FORUM_PRIV'
GO
DELETE FROM b_option WHERE (MODULE_ID = 'forum') AND ((NAME LIKE 'FILTER%') OR (NAME LIKE 'MESSAGE_HTML%'))
GO
