DROP TABLE B_VOTE_CHANNEL CASCADE CONSTRAINTS
/
DROP TABLE B_VOTE_CHANNEL_2_GROUP CASCADE CONSTRAINTS
/
DROP TABLE B_VOTE_CHANNEL_2_SITE CASCADE CONSTRAINTS 
/
DROP TABLE B_VOTE CASCADE CONSTRAINTS 
/
DROP TABLE B_VOTE_QUESTION CASCADE CONSTRAINTS
/
DROP TABLE B_VOTE_ANSWER CASCADE CONSTRAINTS 
/
DROP TABLE B_VOTE_EVENT CASCADE CONSTRAINTS
/
DROP TABLE B_VOTE_EVENT_QUESTION CASCADE CONSTRAINTS
/
DROP TABLE B_VOTE_EVENT_ANSWER CASCADE CONSTRAINTS
/
DROP TABLE B_VOTE_USER CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_VOTE
/
DROP SEQUENCE SQ_B_VOTE_ANSWER
/
DROP SEQUENCE SQ_B_VOTE_CHANNEL
/
DROP SEQUENCE SQ_B_VOTE_CHANNEL_GROUP
/
DROP SEQUENCE SQ_B_VOTE_EVENT
/
DROP SEQUENCE SQ_B_VOTE_EVENT_ANSWER
/
DROP SEQUENCE SQ_B_VOTE_EVENT_QUESTION
/
DROP SEQUENCE SQ_B_VOTE_QUESTION
/
DROP SEQUENCE SQ_B_VOTE_USER
/