DELETE FROM b_agent WHERE MODULE_ID='iblock'
/
DROP TABLE b_iblock_type CASCADE CONSTRAINTS
/
DROP TABLE b_iblock_site CASCADE CONSTRAINTS
/
DROP TABLE b_iblock_type_lang CASCADE CONSTRAINTS
/
DROP TABLE b_iblock CASCADE CONSTRAINTS
/
DROP SEQUENCE sq_b_iblock
/
DROP TABLE b_iblock_property  CASCADE CONSTRAINTS
/
DROP SEQUENCE sq_b_iblock_property
/
DROP TABLE b_iblock_section CASCADE CONSTRAINTS
/
DROP SEQUENCE sq_b_iblock_section
/
DROP TABLE b_iblock_element CASCADE CONSTRAINTS
/
DROP SEQUENCE sq_b_iblock_element
/
DROP TABLE b_iblock_element_property CASCADE CONSTRAINTS
/
DROP SEQUENCE sq_b_iblock_element_property
/
DROP TABLE b_iblock_group CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_IBLOCK_RSS
/
DROP TABLE B_IBLOCK_RSS CASCADE CONSTRAINTS
/
DROP TABLE B_IBLOCK_CACHE CASCADE CONSTRAINTS
/
DROP TABLE B_IBLOCK_PROPERTY_ENUM CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_IBLOCK_PROPERTY_ENUM
/
DROP TABLE B_IBLOCK_SECTION_ELEMENT CASCADE CONSTRAINTS
/
