TRUNCATE TABLE B_FORM
GO
TRUNCATE TABLE B_FORM_2_MAIL_TEMPLATE
GO
TRUNCATE TABLE B_FORM_2_SITE
GO
TRUNCATE TABLE B_FORM_ANSWER
GO
TRUNCATE TABLE B_FORM_FIELD
GO
TRUNCATE TABLE B_FORM_FIELD_FILTER
GO
TRUNCATE TABLE B_FORM_FIELD_VALIDATORS
GO
TRUNCATE TABLE B_FORM_MENU
GO
TRUNCATE TABLE B_FORM_RESULT
GO
TRUNCATE TABLE B_FORM_RESULT_ANSWER
GO
TRUNCATE TABLE B_FORM_2_GROUP
GO
TRUNCATE TABLE B_FORM_STATUS_2_GROUP
GO
TRUNCATE TABLE B_FORM_STATUS
GO