DROP TABLE B_FORM
GO
DROP TABLE B_FORM_2_MAIL_TEMPLATE
GO
DROP TABLE B_FORM_2_SITE
GO
DROP TABLE B_FORM_ANSWER
GO
DROP TABLE B_FORM_FIELD
GO
DROP TABLE B_FORM_FIELD_FILTER
GO
DROP TABLE B_FORM_FIELD_VALIDATOR
GO
DROP TABLE B_FORM_MENU
GO
DROP TABLE B_FORM_RESULT
GO
DROP TABLE B_FORM_RESULT_ANSWER
GO
DROP TABLE B_FORM_2_GROUP
GO
DROP TABLE B_FORM_STATUS_2_GROUP
GO
DROP TABLE B_FORM_STATUS
GO
DROP FUNCTION dbo.CONVERT_TO_NUMBER
GO