document.write('</div>');
document.write('<img height="120" width="720" src="/8days/image/20_percent_.gif" /> ');
document.write('<br />'); 
document.write('<table height="20" width="100%" cellspacing="1" cellpadding="1" border="0" align="center"> ');
document.write('<tbody> ');
document.write('<tr><td><a href="/catalog/divan160.htm"><img height="115" width="230" src="/upload/iblock/cfe/arizona.jpg" /></a></td> <td><a href="/catalog/divan162.htm"><img height="115" width="230" src="/upload/iblock/a95/kentukki_230x115_s.jpg" /></a></td> <td><a href="/catalog/divan520.htm"><img height="115" width="230" src="/8days/image/tennessee_230x115.jpg" /></a></td> </tr>');   
document.write('<tr> <td><img height="36" width="231" src="/8days/image/20--_arzona.gif" /></td> <td><img height="36" width="231" src="/8days/image/20--_kentuky.gif" /></td> <td><img height="36" width="230" src="/8days/image/20--_tennesee.gif" /></td> </tr>');   
document.write('<tr> <td><a href="/catalog/divan1683.htm"><img height="115" width="230" src="/upload/iblock/d9c/Marseille_nov_.jpg" alt="спальное место с блоком независимых пружин!" /></a></td> <td><a href="/catalog/divan144.htm"><img height="115" width="230" src="/upload/iblock/00b/neapol.jpg" /></a></td> <td><a href="/catalog/divan143.htm"><img height="115" width="230" src="/upload/iblock/436/antalia_1.jpg" /></a></td></tr>');   
document.write('<tr> <td><img height="36" width="230" src="/8days/image/20--_marsel.gif" /></td> <td><img height="37" width="230" src="/8days/image/neapol_cena.gif" /></td> <td><img height="37" width="230" src="/8days/image/antalia_cena.gif" /></td></tr>');   
document.write('<tr><td><a href="/catalog/divan544.htm"><img height="115" width="230" src="/upload/iblock/492/nelson1.jpg" /></a></td></td> <td></td></tr>');   
document.write('<tr><td><img height="36" width="231" src="/8days/image/20--_nelson.gif" /></td> <td></td> <td></td></tr>');  
document.write('<tr> <td></td> <td></td><td></td> </tr>');   
document.write('<tr> <td></td> <td></td><td></td> </tr>');   
document.write('<tr><td></td><td></td><td></td></tr>');   
document.write('<tr><td></td><td></td><td></td></tr>');
document.write('</tbody>');
document.write('</table>');
document.write('<font size="3" color="#FF0000"><strong>28 февраля</strong> заканчивается акция &laquo;Скидка 20% на хиты продаж&raquo; в салонах Москвы и области. Не упустите уникальную возможность приобрести мягкую мебель фабрики &laquo;Авангард&raquo; со скидкой <font size="5"><strong>20</strong>%</font>.</font> ');
document.write('<br />');