document.write('<div class="gray_td"> ');
document.write('<h1>АКЦИЯ В САНКТ-ПЕТЕРБУРГЕ: СКИДКА 20% НА МОДЕЛИ &quot;ОРЕГОН&quot; И &quot;РИЧМОНД&quot;</h1>');
document.write('</div>'); 
document.write('<table height="20" width="100%" cellspacing="1" cellpadding="1" border="0" align="center">');
document.write('<tbody> ');
document.write('<tr><td><a href="/catalog/divan475.htm" target="_blank" ><img height="200" width="350" border="0" src="/8days/image/oregon-20.jpg" /></a></td>'); 
document.write('<td><a href="/catalog/divan475.htm"  target="_blank" ><img height="200" width="350" border="0" src="/8days/image/richmond-20.jpg" /></a></td> <td></td></tr>'); 
document.write('<tr><td>Орегон </td> <td>Ричмонд</td> <td></td></tr>'); 
document.write('<tr> <td></td> <td></td><td></td> </tr>');   
document.write('<tr> <td></td> <td></td><td></td> </tr>');  
document.write('</tbody>');
document.write('</table>');
document.write('<font size="3">Акция в салонах Санкт-Петербурга! ');
document.write('<br />');
document.write('С 22 по 31 января <b>cкидка<font color="#ff0000"> 20%</font></b> на популярные модели &quot;Орегон&quot; и &quot;Ричмонд&quot;.');
document.write('<br />');
document.write('<font color="#f16522"><b>Спешите приобрести лучшие в своем классе диваны-кровати по ценам акции!</b></font></font>');
document.write('<br />');
document.write('<br />');