<?
$MESS ['SEC_OTP_NOTE'] = "<h3 style=\"clear:both\"><br />One-Time-Password</h3><img src=\"/bitrix/images/security/etoken_pass.png\" align=\"left\" style=\"margin-right:10px;\">Das <a href=\"http://de.wikipedia.org/wiki/Einmalpasswort\" target=\"_blank\">One-Time-Password System</a> ergänzt das vorhandene Autorisierungssystem und erhöht die Sicherheit Ihres Projekts. Um das System nutzen zu können, brauchen Sie einen eToken PASS wie z.B. von <a href=\"http://www.safenet-inc.com/products/data-protection/two-factor-authentication/etoken-pass/\">SafeNet</a> oder eine Lösung, die Standard OTP unterstützt. Empfehlenswert ist es, dieses System für die Administratoren einzusetzen, weil damit die Sicherheitsstufe dieser Usergruppe erheblich erhöht wird.<h3 style=\"clear:both\"><br />Anleitung</h3><img src=\"/bitrix/images/security/de_pass_form.png\" align=\"left\" style=\"margin-right:10px;\">Wenn das OTP-System aktiv ist, kann sich der User nur mit seinem Loginnamen und der Kombination zwischen dem eigenen Passwort und dem Einmalpasswort anmelden. Das Einmalpasswort (siehe <font style=\"color:red\">2</font> auf der Abbildung) wird in der Anmeldemaske im Feld \"Passwort\" direkt nach dem eigenen Passwort (siehe <font style=\"color:red\">1</font> auf der Abbildung) ohne Leerzeichen eingegeben.<br />Der erweiterter Anmeldeprozess wird erst dann aktiv, wenn ein geheimes Kennwort (ggKW) und <b>zwei nacheinander generierten Einmalpasswörter</b> in das System eingegeben werden.<h3 style=\"clear:both\"><br />Initialisierung</h3>Bei der Initialisierung oder der Reinitialisierung zwischen dem Client und Server werden <b>zwei nacheinander generierte Einmalpasswörter</b> eingegeben.<h3 style=\"clear:both\"><br />Beschreibung</h3>Der Anmeldeprozess mit dem Einmalpasswort wurde im Rahmen der <a href=\"http://www.openauthentication.org/\" target=\"_blank\">OATH</a> Initiative entwickelt.<br />Die Realisierung wurde mit dem HMAC Algorithmus und der SHA-1 Hash-Funktion umgesetzt. Das Einmalpasswort wird aus zwei Parametern ermittelt: geheimes Kennwort (ggKW) und aktuelle Werte, die vom Generator zurückgegeben werden. Nach der Initialisierung wird der erste Wert im System sowie auf dem Server gespeichert. Der Zähler im System wird bei jeder Generierung des Einmalpassworts erhöht, auf dem Server bei jeder erfolgreichen Autorisierung.<br />Die OTP-Systeme verfügen über eine kodierte Datei, die das gemeine Kennwort (ggKW) liefert.";
$MESS ['SEC_OTP_SWITCH_ON'] = "Zusammengesetztes Passwort aktivieren";
$MESS ['SEC_OTP_INIT'] = "Initialisierung";
$MESS ['SEC_OTP_SECRET_KEY'] = "Geheimes Kennwort (wird mit dem Gerät mitgeliefert)";
$MESS ['SEC_OTP_PASS1'] = "Der erste Wert des Passworts (drücken Sie die Taste auf dem Gerät)";
$MESS ['SEC_OTP_PASS2'] = "Weiterer Wert des Passworts (drücken Sie erneut die Taste auf dem Gerät)";
$MESS ['SEC_OTP_ACCESS_DENIED'] = "Die Verwaltung der One-Time-Passwords ist nicht möglich.";
?>
