<?
$arTooltips = array(
	"CACHE_TYPE" => GetMessage("CACHE_TYPE_TIP"),
	"CACHE_TIME" => GetMessage("CACHE_TIME_TIP"),
	"URL_TEMPLATES_INDEX" => GetMessage("URL_TEMPLATES_INDEX_TIP"),
	"URL_TEMPLATES_LIST" => GetMessage("URL_TEMPLATES_LIST_TIP"),
	"URL_TEMPLATES_PROFILE_VIEW" => GetMessage("URL_TEMPLATES_PROFILE_VIEW_TIP"),
	"URL_TEMPLATES_SUBSCR_LIST" => GetMessage("URL_TEMPLATES_SUBSCR_LIST_TIP"),
	"URL_TEMPLATES_ACTIVE" => GetMessage("URL_TEMPLATES_ACTIVE_TIP"),
	"URL_TEMPLATES_SEARCH" => GetMessage("URL_TEMPLATES_SEARCH_TIP"),
	"URL_TEMPLATES_HELP" => GetMessage("URL_TEMPLATES_HELP_TIP"),
	"URL_TEMPLATES_USER_LIST" => GetMessage("URL_TEMPLATES_USER_LIST_TIP"),
	"URL_TEMPLATES_PM_LIST" => GetMessage("URL_TEMPLATES_PM_LIST_TIP"),
	"URL_TEMPLATES_PM_EDIT" => GetMessage("URL_TEMPLATES_PM_EDIT_TIP"),
	"URL_TEMPLATES_PM_FOLDER" => GetMessage("URL_TEMPLATES_PM_FOLDER_TIP"),
	"URL_TEMPLATES_RULES" => GetMessage("URL_TEMPLATES_RULES_TIP"),
	"FID" => GetMessage("FID_TIP"),
	"TID" => GetMessage("TID_TIP"),
	"PAGE_NAME" => GetMessage("PAGE_NAME_TIP"),
	"PATH_TO_AUTH_FORM" => GetMessage("PATH_TO_AUTH_FORM_TIP"),
);
?>