DROP TABLE B_LANG CASCADE CONSTRAINTS
/
DROP TABLE B_EVENT_TYPE  CASCADE CONSTRAINTS
/
DROP TABLE B_EVENT_MESSAGE CASCADE CONSTRAINTS
/
DROP TABLE B_EVENT CASCADE CONSTRAINTS
/
DROP TABLE B_GROUP CASCADE CONSTRAINTS
/
DROP TABLE B_USER CASCADE CONSTRAINTS
/
DROP TABLE B_USER_GROUP CASCADE CONSTRAINTS
/
DROP TABLE B_MODULE CASCADE CONSTRAINTS
/
DROP TABLE B_AGENT CASCADE CONSTRAINTS
/
DROP TABLE B_OPTION CASCADE CONSTRAINTS
/
DROP TABLE B_MODULE_TO_MODULE CASCADE CONSTRAINTS
/
DROP TABLE B_FILE CASCADE CONSTRAINTS
/
DROP TABLE B_FILE_ACTION CASCADE CONSTRAINTS
/
DROP TABLE B_MODULE_GROUP CASCADE CONSTRAINTS
/
DROP TABLE B_FAVORITE CASCADE CONSTRAINTS
/
DROP TABLE B_USER_STORED_AUTH CASCADE CONSTRAINTS
/
DROP TABLE B_USER_OPTION CASCADE CONSTRAINTS
/
DROP TABLE B_CAPTCHA CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_EVENT_TYPE
/
DROP SEQUENCE SQ_B_FILE_ACTION
/
DROP SEQUENCE SQ_B_FILE
/
DROP SEQUENCE SQ_B_AGENT
/
DROP SEQUENCE SQ_B_EVENT_MESSAGE
/
DROP SEQUENCE SQ_B_EVENT
/
DROP SEQUENCE SQ_B_USER
/
DROP SEQUENCE SQ_B_GROUP
/
DROP SEQUENCE SQ_B_MODULE_GROUP
/
DROP SEQUENCE SQ_B_FAVORITE
/
DROP SEQUENCE SQ_B_MODULE_TO_MODULE
/
DROP SEQUENCE SQ_B_USER_STORED_AUTH
/
DROP SEQUENCE SQ_B_USER_OPTION
/