DELETE FROM b_agent WHERE MODULE_ID='iblock'
GO
ALTER TABLE B_IBLOCK DROP CONSTRAINT FK_B_IBLOCK_B_IBLOCK_TYPE
GO
ALTER TABLE B_IBLOCK_PROPERTY DROP CONSTRAINT FK_B_IBLOCK_PROPERTY_B_IBLOCK
GO
ALTER TABLE B_IBLOCK_SECTION DROP CONSTRAINT FK_B_IBLOCK_SECTION_B_IBLOCK
GO
ALTER TABLE B_IBLOCK_SECTION DROP CONSTRAINT FK_B_IBLOCK_SECTION_B_IBLOCK_SECTION
GO
ALTER TABLE B_IBLOCK_ELEMENT DROP CONSTRAINT FK_B_IBLOCK_ELEMENT_B_IBLOCK
GO
ALTER TABLE B_IBLOCK_ELEMENT DROP CONSTRAINT FK_B_IBLOCK_ELEMENT_B_IBLOCK_SECTION
GO
ALTER TABLE B_IBLOCK_ELEMENT_PROPERTY DROP CONSTRAINT FK_B_IBLOCK_ELEMENT_PROPERTY_B_IBLOCK_PROPERTY
GO
ALTER TABLE B_IBLOCK_ELEMENT_PROPERTY DROP CONSTRAINT FK_B_IBLOCK_ELEMENT_PROPERTY_B_IBLOCK_ELEMENT
GO
ALTER TABLE B_IBLOCK_PROPERTY_ENUM DROP CONSTRAINT FK_B_IBLOCK_PROPERTY_ENUM_PROPERTY_ID
GO
ALTER TABLE B_IBLOCK_GROUP DROP CONSTRAINT FK_B_IBLOCK_GROUP_B_IBLOCK
GO
ALTER TABLE B_IBLOCK_SECTION_ELEMENT DROP CONSTRAINT FK_B_IBLOCK_SECTION_ELEMENT_B_IBLOCK_ELEMENT
GO
ALTER TABLE B_IBLOCK_SECTION_ELEMENT DROP CONSTRAINT FK_B_IBLOCK_SECTION_ELEMENT_B_IBLOCK_SECTION
GO
ALTER TABLE B_IBLOCK_RSS DROP CONSTRAINT FK_B_IBLOCK_RSS_B_IBLOCK
GO
DROP TABLE B_IBLOCK
GO
DROP TABLE B_IBLOCK_TYPE
GO
DROP TABLE B_IBLOCK_SITE
GO
DROP TABLE B_IBLOCK_TYPE_LANG
GO
DROP TABLE B_IBLOCK_PROPERTY
GO
DROP TABLE B_IBLOCK_SECTION
GO
DROP TABLE B_IBLOCK_ELEMENT
GO
DROP TABLE B_IBLOCK_ELEMENT_PROPERTY
GO
DROP TABLE B_IBLOCK_GROUP
GO
DROP TABLE B_IBLOCK_RSS
GO
DROP TABLE B_IBLOCK_CACHE
GO
DROP TABLE B_IBLOCK_PROPERTY_ENUM
GO
DROP TABLE B_IBLOCK_SECTION_ELEMENT
GO