<?
$arTooltips = array(
	"UID" => GetMessage("UID_TIP"),
	"URL_TEMPLATES_LIST" => GetMessage("URL_TEMPLATES_LIST_TIP"),
	"URL_TEMPLATES_READ" => GetMessage("URL_TEMPLATES_READ_TIP"),
	"URL_TEMPLATES_MESSAGE" => GetMessage("URL_TEMPLATES_MESSAGE_TIP"),
	"URL_TEMPLATES_PROFILE_VIEW" => GetMessage("URL_TEMPLATES_PROFILE_VIEW_TIP"),
	"URL_TEMPLATES_SUBSCR_LIST" => GetMessage("URL_TEMPLATES_SUBSCR_LIST_TIP"),
	"TOPICS_PER_PAGE" => GetMessage("TOPICS_PER_PAGE_TIP"),
	"DATE_TIME_FORMAT" => GetMessage("DATE_TIME_FORMAT_TIP"),
	"PAGE_NAVIGATION_TEMPLATE" => GetMessage("PAGE_NAVIGATION_TEMPLATE_TIP"),
	"PAGE_NAVIGATION_WINDOW" => GetMessage("PAGE_NAVIGATION_WINDOW_TIP"),
	"SET_NAVIGATION" => GetMessage("SET_NAVIGATION_TIP"),
	"DISPLAY_PANEL" => GetMessage("DISPLAY_PANEL_TIP"),
	"SET_TITLE" => GetMessage("SET_TITLE_TIP"),
);
?>